//==================================================
// This file contains the Excluded objects
// Generated By User: host
// Format Version: 2
// Date: Wed Aug 16 11:02:32 2023
// ExclMode: default
//==================================================
CHECKSUM: "2158471359"
INSTANCE:uvm_custom_install_verdi_recording
CHECKSUM: "152008218 2944321845"
INSTANCE: serial_rx_top.U_SERIAL_RX
Fsm state "2944321845"
Transition DATA_DETECT->PRE_DETECT "3->0"
CHECKSUM: "3266273916 2134916063"
INSTANCE: serial_rx_top.U_SERIAL_RX.U_COUNTER_4
Toggle count [2] "reg count[2:0]"
